---

kind: pipeline
name: ansible-ci
workspace:
  base: /drone
  path: src/${DRONE_REPO}

steps:
  # - name: molecule
  #   image: lowess/drone-molecule:2.6.8
  #   environment:
  #     CI_UUID: _2.6_${DRONE_COMMIT_SHA:0:8}
  #     ANSIBLE_STRATEGY: mitogen_linear
  #   pull: true
  #   settings:
  #     task: test
  #   volumes:
  #     - name: dockersock
  #       path: /var/run/docker.sock

  - name: galaxy
    image: lowess/drone-molecule:2.6.8
    environment:
      GALAXY_TOKEN:
        from_secret: ansible_galaxy_token
    commands:
      - ansible-galaxy login --github-token $GALAXY_TOKEN

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
