---

kind: pipeline
name: ansible-ci
workspace:
  base: /drone
  path: src/${DRONE_REPO}

molecule: &molecule
  pull: true
  settings:
    task: test
  volumes:
    - name: dockersock
      path: /var/run/docker.sock
  group: molecule

steps:
  - name: molecule-2.4
    image: lowess/drone-molecule:2.4.6.0
    environment:
      CI_UUID: _2.4_${DRONE_COMMIT_SHA:0:8}
      ANSIBLE_STRATEGY: mitogen_linear
    <<: *molecule

  - name: molecule-2.5
    image: lowess/drone-molecule:2.5.8
    environment:
      CI_UUID: _2.5_${DRONE_COMMIT_SHA:0:8}
      ANSIBLE_STRATEGY: mitogen_linear
    <<: *molecule

  - name: molecule-2.6
    image: lowess/drone-molecule:2.6.8
    environment:
      CI_UUID: _2.6_${DRONE_COMMIT_SHA:0:8}
      ANSIBLE_STRATEGY: mitogen_linear
    <<: *molecule

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
