---

kind: pipeline
name: ansible-ci
workspace:
  base: /drone
  path: src/${DRONE_REPO}

molecule: &molecule
  pull: true
  settings:
    task: test
  volumes:
    - name: dockersock
      path: /var/run/docker.sock

steps:
  - name: molecule-2.2
    image: lowess/drone-molecule:2.2.3.0
    <<: *molecule

  - name: molecule-2.6
    image: lowess/drone-molecule:2.6.8
    environment:
      ANSIBLE_STRATEGY: mitogen_linear
    <<: *molecule

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
