---
proxy_env:
  http_proxy: "http://{{ lookup('env', 'PROXY_URL') }}:3128"
  https_proxy: "http://{{ lookup('env', 'PROXY_URL') }}:3128"
  HTTP_PROXY: "http://{{ lookup('env', 'PROXY_URL') }}:3128"
  HTTPS_PROXY: "http://{{ lookup('env', 'PROXY_URL') }}:3128"
